### ISSUE TITLE
Issues from Fake Filler

### ISSUE THREAD

**Issue by calvinballing** [calvinballing/fake-filler-extension#1]
Issues carried over from original Fake Filler.

# Completed, Duplicate, or question has been addressed

- [x] https://github.com/FakeFiller/fake-filler-extension/issues/197 (opened on Apr 17 by Tom5om)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/196 (opened on Jan 26 by YoungbloodTheOne)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/190 (opened on Sep 9, 2022 by siba2893)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/179 (opened on Apr 18, 2022 by niuxiansen2)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/174 (opened on Jan 27, 2022 by lucianobosco)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/168 (opened on Sep 2, 2021 by jodaches)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/165 (opened on Jul 7, 2021 by shivapoudel)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/157 (opened on Apr 1, 2021 by alexandredepape)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/155 (opened on Mar 10, 2021 by anishmm)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/153 (opened on Jan 28, 2021 by vasilyevanton24)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/140 (opened on Sep 9, 2020 by Mike3285)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/137 (opened on Jul 20, 2020 by tarekis)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/76 (opened on Apr 24, 2018 by madhugilla)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/142 (opened on Oct 8, 2020 by list5066)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/163 (opened on Jun 8, 2021 by gouthamravee)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/56 (opened on Sep 6, 2017 by chuckoy)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/189 (opened on Sep 2, 2022 by IamHaiderRasheed)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/100 (opened on May 3, 2019 by jordyvandomselaar)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/139 (opened on Aug 27, 2020 by tulik)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/186 (opened on Aug 11, 2022 by RaviRamDhali)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/185 (opened on Jul 28, 2022 by HurayraIIT)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/198 (opened on May 29 by rickallauigan)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/133 (opened on Jul 7, 2020 by zisan34)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/199 (opened on Aug 12 by genialkartik) - Fake Filler 2 doesn't yet have Firefox support, and this was Firefox only
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/101 (opened on May 5, 2019 by Marco-Sulla)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/59 (opened on Oct 3, 2017 by mblander)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/195 (opened on Jan 26 by tuhin-ccm)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/180 (opened on May 11, 2022 by i1group)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/187 (opened on Aug 21, 2022 by codemonkey76)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/172 (opened on Oct 22, 2021 by cee0621)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/132 (opened on Jun 14, 2020 by MuathIbnHassan) - v1 version of file upload has been added.  Could use enhancements such as custom user file upload.

# Feature Requests

## Prevent unwanted filling
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/149 (opened on Dec 25, 2020 by DKWLB)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/145 (opened on Nov 26, 2020 by devanshdiwanji)

## Enhance Existing Filling

- [x] https://github.com/FakeFiller/fake-filler-extension/issues/138 (opened on Aug 19, 2020 by LeBaux)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/173 (opened on Nov 5, 2021 by AoiRei)
 - [x] minlength
 - [x] maxlength
 - [x] min
 - [x] max
 - [x] pattern
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/144 (opened on Nov 24, 2020 by kythuatwebso)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/105 (opened on Aug 26, 2019 by mthurmond)
- [x] https://github.com/FakeFiller/fake-filler-extension/issues/183 (opened on Jul 15, 2022 by rolltidehero)

## Fill in new places or new ways

- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/167 (opened on Aug 13, 2021 by arunsathiya)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/148 (opened on Dec 21, 2020 by LinqLover)

## Autocomplete

- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/99 (opened on Mar 26, 2019 by w3l)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/188 (opened on Aug 30, 2022 by lockepratt)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/171 (opened on Oct 7, 2021 by DonRichards)

## Other Features

- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/151 (opened on Jan 19, 2021 by megamx28)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/121 (opened on Feb 22, 2020 by dwengs)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/117 (opened on Jan 15, 2020 by GeorgeWL)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/141 (opened on Oct 2, 2020 by brodenbrett)

# Bugs
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/51 (opened on May 12, 2017 by ghost)
- [ ] https://github.com/FakeFiller/fake-filler-extension/issues/170 (opened on Sep 13, 2021 by ken-colvin)
